### ISSUE TITLE
Outdated or Untrusted Dependencies

### ISSUE THREAD

**Issue by sshubhamagg** [getsafle/safle-vault#207]
Update all outdated dependencies and remove any untrusted dependency

**Comment by apoorvq** [comment]
Analysis of Dependencies complete. Results are here: 

package | version used | current version |   | Action Pending
bip39 | 3.0.4 | 3.1.0 | To be updated. All methods used are same | Update
browser-passworder | 2.0.3 | 2.0.3 | N/A | Remove if not used
crypto | 1.0.1 | deprecated/ now built-in | To be removed and vault sdk to be tested | Remove if not used
crypto-js | 4.0.0 | 4.1.1 | To be updated | Update
eth-hd-keyring | 3.6.0 | 3.6.0 | N/A | remove
ethereumjs-util | 7.1.2 | 7.1.5 | To be removed and vault sdk to be tested | remove
ethers | 5.5.3 | 6.3.0 | To be updated and validate validateMnemonic method | update and test
get-random-values | 1.2.2 | 2.1.0 | to be updated. Also update node to v18 and update pipelines | update
jest | 29.4.3 | 29.5.0 | N/A | no action required.
lodash | 4.17.21 | 4.17.21 | N/A | no action required
loglevel | 1.7.1 | 1.8.1 | To be removed and vault sdk to be tested | Remove
obs-store | 4.0.3 | 4.0.3 | N/A | no action required
web3 | 1.3.5 | 1.9.0 | To be updated. No changes | update and test
@ethereumjs/common | 2.5.0 | 3.1.2 | To be removed and vault sdk to be tested | remove
@ethereumjs/tx | 3.3.2 | 4.1.2 | To be removed and vault sdk to be tested | remove
@getsafle/asset-controller | 1.0.9 | 1.0.10 | Yo be updated. No breaking changes | update
@getsafle/safle-identity-wallet | 1.3.0 | 1.3.0 | N/A | no action required
@getsafle/transaction-controller | 1.9.1 | 1.9.3 | To be updated. no breaking changes | update and test
@getsafle/vault-bitcoin-controller | 1.2.3 | 1.2.3 | N/A | no action required
@getsafle/vault-bsc-controller | 1.2.0 | 1.2.0 | N/A | no action required
@getsafle/vault-eth-controller | 1.4.1 | 1.4.1 | N/A | no action required
@getsafle/vault-polygon-controller | 1.2.3 | 1.2.3 | N/A | no action required
